---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: \.gitignore

  - repo: local
    hooks:
      - id: python-format
        name: Format Python files
        description: Format Python files
        language: system
        entry: make format
        types_or:
          - python
          - pyi

      - id: python-lint
        name: Lint Python files
        description: Lint Python files
        language: system
        entry: make lint
        args:
          - LINT_OPTIONS=--fix --exit-non-zero-on-fix
        types_or:
          - python
          - pyi

      - id: test
        name: Run tests
        description: Run tests
        language: system
        entry: make test
        types_or:
          - python
          - pyi

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 84080c769d17e250eb32ac0d10662c7bf03ad346  # frozen: 0.31.3
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: 23eab0f0eedcbedebff420f5fdfb284744adc7b3  # frozen: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint

  - repo: https://github.com/lyz-code/yamlfix
    rev: 8072181c0f2eab9f2dd8db2eb3b9556d7cd0bd74  # frozen: 1.17.0
    hooks:
      - id: yamlfix
        args:
          - --config-file
          - .yamlfix.toml

  - repo: https://github.com/adrienverge/yamllint
    rev: be92e15345b32661abee2e675d765ae79686eb4c  # frozen: v1.37.0
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 586c3ea3f51230da42bab657c6a32e9e66c364f0  # frozen: v0.44.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/sirwart/ripsecrets
    rev: 033ec5192b738b6712701be920cba545c2775050  # frozen: v0.1.8
    hooks:
      - id: ripsecrets

  - repo: https://github.com/crate-ci/typos
    rev: 2300ad1b6b5c37da54bcafb1a06211196503eac9  # frozen: v1
    hooks:
      - id: typos
        args: []
